name: Android CI

on:
  push:
    paths:
    - 'Mobile-application/Android/**'
  pull_request:
    paths:
    - 'Mobile-application/Android/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      working-directory: ./Mobile-application/Android
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      working-directory: ./Mobile-application/Android
      run: ./gradlew build