name: APOLLO CI

on:
  push:
    paths:
    - 'Backend/apollo-graphql-mongoDB/**'
  pull_request:
    paths:
    - 'Backend/apollo-graphql-mongoDB/**'

jobs:
  apollo-job:
    name: APOLLO CI Job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: '12.x'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ./Backend/apollo-graphql-mongoDB
    - run: npm run build --if-present
      working-directory: ./Backend/apollo-graphql-mongoDB
    - run: npm test
      working-directory: ./Backend/apollo-graphql-mongoDB