name: Docker Image CI

on:
  push:
    paths:
    - 'Docker/**'
  pull_request:
    paths:
    - 'Docker/**'

jobs:

  build:
    name: DOCKER CI job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./Docker
      run: docker build . --file Dockerfile --tag checksie:$(date +%s)
