name: Swift CI

on:
  push:
    paths:
    - 'Mobile-application/IOS/**'
  pull_request:
    paths:
    - 'Mobile-application/IOS/**'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./Mobile-application/IOS
      run: swift build -v
    - name: Run tests
      working-directory: ./Mobile-application/IOS
      run: swift test -v